oc_platform_app:
    path: /
    defaults:
        _controller: OCPlatformBundle:App:index

oc_platform_homepage:
    path:     /platform/{page}
    defaults:
        _controller: OCPlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*

oc_platform_view:
    path:     /platform/advert/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:view
    requirements:
        id: \d+

oc_platform_add:
    path:     /platform/add
    defaults:
        _controller: OCPlatformBundle:Advert:add

oc_platform_edit:
    path:     /platform/edit/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:edit
    requirements:
        id: \d+

oc_platform_delete:
    path:     /platform/delete/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:delete
    requirements:
        id: \d+

oc_platform_menu:
    path:     /platform/menu
    defaults:
        _controller: OCPlatformBundle:Advert:menu

oc_platform_applications_list:
    path:     /platform/applications
    defaults:
        _controller: OCPlatformBundle:Application:index

oc_platform_application_add:
    path: /platform/application/add/{advertId}
    defaults:
        _controller: OCPlatformBundle:Application:Add

oc_platform_application_edit:
    path: /platform/application/edit/{applicationId}
    defaults:
        _controller: OCPlatformBundle:Application:Edit

oc_platform_application_delete:
    path: /platform/application/delete/{applicationId}
    defaults:
        _controller: OCPlatformBundle:Application:Delete
