<?php

namespace OC\PlatformBundle\Repository;

use \Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{

  public function getAdverts($page, $nbPerPage)
  {
    $qb = $this->createQueryBuilder('a')
      ->leftJoin('a.image', 'i')
      ->addSelect('i')
      ->leftJoin('a.categories', 'c')
      ->addSelect('c')
      ->orderBy('a.date', 'DESC')
      ->getQuery()
    ;

    $qb->setFirstResult(($page-1)*$nbPerPage)
      ->setMaxResults($nbPerPage)
    ;

    return new Paginator($qb, true);
  }

  public function getAdvertWithCategories(array $categoryNames)
  {
    $qb = $this
      ->createQueryBuilder('a')
      ->innerJoin('a.categories', 'cat')
      ->addSelect('cat');

    $qb->where($qb->expr()->in('cat.name', $categoryNames));

    return $qb->getQuery()->getResult();
  }
}
